services:
  - type: web
    name: frontend-proyectofinal-caninestylist
    env: static
    plan: free
    buildCommand: 'npm install && npm run build'
    staticPublishPath: 'dist'
    envVars:
      - key: VITE_API_URL
        value: url-de-tu-backend-en-render
