services:
  - type: web
    name: backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    port: 3000
    envVars:
      - key: DATABASE_URL
        value: postgresql://nitolez:mUtVdue0CtEubGmOlhC4Kp0ZIZ4F1tX9@dpg-cqbdqetumphs73d2kthg-a.oregon-postgres.render.com/caninestylist
    healthCheckPath: "/api/health"

  - type: static
    name: frontend
    buildCommand: "npm install && npm run build"
    publishDirectory: "dist"
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://caninestylistapi.onrender.com
